workflows: 
  gitlab_patched_build:
    name: GitLab PAT Build
    environment:
      #groups:
      #  - GitLabToken
      vars:
        GITLABPAT: $GITLABPAT # This variable will be set by the API trigger
        REPO_URL: "https://oauth2:$GITLABPAT@gitlab.com/ivan-group3770550/ivan-project.git"
    pre_clone_scripts:
      - name: Send build status to GitLab
        script: |
          echo "GITLABPAT=$GITLABPAT"
      - name: Clone with GitLab PAT
        script: |
          echo "test pre-clone script"
          git clone "$REPO_URL" ./gitlab-repo --branch="master" --depth=1
          cd gitlab-repo
          echo "Real repo cloned to: $(pwd)"
  
    scripts:
      - name: Build from REAL GitLab repo
        script: |
          cd gitlab-repo
          echo "Building from REAL repo: $(pwd)"
          ls -la  # List real repo contents
          # Your iOS/Android build commands HERE
          echo "✅ Build complete!"
